add basic test examples
anditru/quickie pull request #28
Opened 2022-02-19 12:34 UTC by imkgerC

Those surely should not count as 8 tests but 2 - should we use JUnit 4 or JUnit 5? JUnit5 allows one to write parametrized tests pretty easiliy
Furthermore: Should we use a library for fluent assertions?

2022-02-19 12:46 UTC, anditru commented
If JUnit 5 provides more functionality, then definitely JUnit 5. Or is there any disadvantage in JUnit 5?
We should indeed use a library for fluent assertions.

2022-02-19 13:09 UTC, imkgerC commented
Is that better?

2022-02-19 13:54 UTC, anditru commented
Way better and I think they are already quite readable. I just think `testNonexistentFromString` would be better named `testInvalidFromString`.

2022-02-21 09:52 UTC, imkgerC commented
![image](https://user-images.githubusercontent.com/24394625/154930762-bd14a017-4471-457e-9b6b-516bc7e3f430.png)

2022-02-21 10:26 UTC, anditru requested changes
Habe in seiner Literatur nachgelesen und die einzige "Namenskonvention", die ich da übereinstimmend gefunden habe, ist das Modell "beschreib halt den Testcase", finde ich aber hässlich. Ich würde die deshalb das Modell "should" vorschlagen, also sowas wie "shoudNotAddOpinionToUnavalableFood" oder so.

2022-02-21 10:26 UTC, anditru commented on 1-quickie-adapters/src/test/java/org/pinkcrazyunicorn/quickie/adapters/mappers/profile/OpinionMapperTest.java
> +    private static Stream<Arguments> provideSuccessfulPairs() {
Hier fängt die Methode mit `provide` an, unten mit `get`. Letzteres finde ich schöner.

2022-02-21 10:53 UTC, anditru requested changes

2022-02-21 10:53 UTC, anditru commented on 1-quickie-adapters/src/test/java/org/pinkcrazyunicorn/quickie/adapters/mappers/profile/OpinionMapperTest.java
> +    public void shouldNotGetInvalidOpinionFromString(String from) {
Wäre da nicht `shouldNotGetOpinionFromInvalidString` treffender?

2022-02-21 10:53 UTC, anditru commented on 2-quickie-application/src/test/java/org/pinkcrazyunicorn/quickie/application/profile/ProfileServiceTest.java
> +    public void shouldSetOpinionAbout() {
`shouldSetOpinionAboutFood`?

2022-02-21 10:53 UTC, anditru commented on 2-quickie-application/src/test/java/org/pinkcrazyunicorn/quickie/application/profile/ProfileServiceTest.java
> +    public void ShouldThrowWhenSettingOpinionForInvalidProfile() {
Bitte Lower CamelCase ^^ Und "should throw" finde ich nicht so schön. Vllt besser "should err".

2022-02-21 10:53 UTC, anditru commented on 2-quickie-application/src/test/java/org/pinkcrazyunicorn/quickie/application/profile/ProfileServiceTest.java
> +    public void shouldThrowWhenMarkingFoodAsAvailableForInvalidProfile() {
"should err"

2022-02-21 10:53 UTC, anditru commented on 2-quickie-application/src/test/java/org/pinkcrazyunicorn/quickie/application/profile/ProfileServiceTest.java
> +    public void shouldThrowWhenRemovingOpinionForInvalidProfile() {
"should err"

2022-02-21 10:53 UTC, anditru commented on 2-quickie-application/src/test/java/org/pinkcrazyunicorn/quickie/application/profile/ProfileServiceTest.java
> +    public void shouldThrowWhenMarkingFoodAsUnavailableForInvalidProfile() {
"should err"

2022-02-21 10:55 UTC, merged